apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-service
spec:
  type: ClusterIP
  selector:
    app: tickets-mongo
  ports:
    - name: tickets-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
